# vim:ft=toml
[[plugins]] # Plugin to easily access Most Recently Used (MRU) files
repo = 'Shougo/neomru.vim'
on_source = 'denite.nvim'
on_path = '.*'

[[plugins]] # Yank
repo = 'Shougo/neoyank.vim'
on_source = 'denite.nvim'
on_event = 'TextYankPost'

[[plugins]] # Dein commands
repo = 'haya14busa/dein-command.vim' 
on_source = ['dein.vim']


[[plugins]] # Python completions
repo = 'zchee/deoplete-jedi'
on_ft = 'python'

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'
hook_add = '''
    " let g:jedi#completions_command = "<C-N>"
    " let g:jedi#use_tabs_not_buffers = 1
    " 補完で次の候補に進むときにtabを使えるという設定にしたつもりですがで
    let g:jedi#popup_select_first = 0 
    " 1個目の候補が入力されるっていう設定を解除
    let g:jedi#popup_on_dot = 0
    " .を入力すると補完が始まるという設定を解除
    " let g:jedi#goto_command = "<leader>d"
    " let g:jedi#goto_assignments_command = "<leader>g"
    " let g:jedi#goto_definitions_command = ""
    " let g:jedi#documentation_command = "K"
    " let g:jedi#usages_command = "<leader>n"
    " let g:jedi#rename_command = "<leader>R"
    " " quick-runと競合しないように大文字Rに変更. READMEだと<leader>r
    " autocmd FileType python setlocal completeopt-=preview
    " ポップアップを表示しない
'''

[[plugins]]
repo = 'lambdalisue/vim-pyenv'
depends = 'jedi-vim'
on_ft = 'python'

